# Generated by Django 3.1 on 2021-03-10 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.BigIntegerField()),
                ('userstatus', models.IntegerField(choices=[(1, 'Registration Completed'), (2, 'Account UnderReview'), (3, 'Accounts Verified')], default=1)),
                ('applicant', models.CharField(blank=True, max_length=100, null=True)),
                ('sodowo', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('dob', models.DateField()),
                ('age', models.IntegerField(default='18')),
                ('pan', models.IntegerField(unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('joining_amt', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('sponsor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sponsor_mobile', models.BigIntegerField(blank=True, null=True)),
                ('referral_code', models.CharField(blank=True, max_length=100, null=True)),
                ('receipt_pic', models.FileField(upload_to='uploads/recepts')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userdetail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('userusage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usrusage', to='accounts.userprofile')),
            ],
        ),
    ]
