# Generated by Django 3.1 on 2021-03-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pan',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
