# Generated by Django 3.1 on 2021-03-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210310_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_referral',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
