# Generated by Django 3.1 on 2021-03-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_user_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sponsor_mobile',
            field=models.BigIntegerField(blank=True, default=1234567890, null=True),
        ),
    ]
