# Generated by Django 3.1 on 2021-03-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210313_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sponsor_mobile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
