# Generated by Django 3.2.1 on 2021-06-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userprofile_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reinvestment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('amount', models.FloatField(null=True)),
            ],
        ),
    ]
