# Generated by Django 3.2.1 on 2021-06-26 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_reinvestment'),
    ]

    operations = [
        migrations.AddField(
            model_name='reinvestment',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
    ]
