# Generated by Django 3.2.1 on 2021-07-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_reinvestment_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='payable',
            name='is_activated',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
