# Generated by Django 3.2.1 on 2021-08-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210719_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_no',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
