# Generated by Django 3.2.1 on 2021-09-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20210820_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='branch_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
