# Generated by Django 3.2.1 on 2021-09-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20210917_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='account_name',
            new_name='accountholder_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
